// API Number to Function Name mapping
export const apiMapping = {
  'A01': 'Register',
  'A02': 'Login',
  'A03': 'Terminate User',
  'A04': 'OTP Verification',
  'A05': 'Refresh',
  'A06': 'Change Password',
  'A07': 'Resend OTP',
  'A08': 'Protected Resources',
  'A09': 'Forgot Password',
  'A10': 'Login External FB/Google',
  'A11': 'Update User Info',
  'A12': 'AddAccountRequest',
  'A13': 'GetAccountDetailRequest',
  'A14': 'BillDetailRequest',
  'A15': 'VASAccountRequest',
  'A16': 'RemoveAccountRequest',
  'A17': 'BIllHistoryRequest',
  'A18': 'BannerDetailRequest',
  'A19': 'CreateFaultRequest',
  'A20': 'ViewFaultList',
  'A21': 'eBillRegistration',
  'A22': 'eBillStatusRequest',
  'A23': 'SMSServiceStatusRequest',
  'A24': 'eBillCheckUserExist',
  'A25': 'OTPeBillAuthRequest',
  'A26': 'SalesLeadCreationRequest',
  'A27': 'BBUsageRequest',
  'A28': 'BillPaymentRequest',
  'A29': 'ProductDetailRequest /ProductDetailRequestV2',
  'A30': 'CallVoiceOTPRequest',
  'A31': 'CheckAppUpdateRequest',
  'A32': 'GetProfileRequest',
  'A33': 'AddAccountVoiceOTPRequest',
  'A34': 'ResendVoiceOTPRequest',
  'A35': 'ProductDetailRequestV2',
  'A36': 'HealthCheckRequest',
  'A37': 'SendOTPRequest',
  'A38': 'VerifyOTPRequest',
  'A39': 'UsageSummaryRequest',
  'A40': 'ExtraGB',
  'A41': 'BonusData',
  'A42': 'FreeData',
  'A43': 'CurrentMonthsDailyUsage',
  'A44': 'PreviousMonthsDailyUsage',
  'A45': 'GetExtraGBPackages',
  'A46': 'PurchaseExtraGBPostpaid',
  'A47': 'PurchaseExtraGBPrepaidInit',
  'A48': 'MyPackage',
  'A49': 'GetAdvancedReportingPackage',
  'A50': 'GetPurchaseHistory',
  'A51': 'WeeksUsage',
  'A52': 'PurchaseExtraGBPrepaidConfirm',
  'A53': 'PurchaseAdvancedReportsPostPaid',
  'A54': 'UnsubscribeAdvancedReports',
  'A55': 'DataGiftEnroll',
  'A56': 'ValidateDataGiftSub',
  'A57': 'DataGiftPackages',
  'A58': 'DataGiftEnrollPrepaidInit',
  'A59': 'DataGiftEnrollPrepaidConfirm',
  'A60': 'RedeemVoucher',
  'A61': 'HappyDay',
  'A62': 'GetVASDataBundlePackages',
  'A63': 'GetReportTimePeriod',
  'A64': 'GetExtraGBPackagesMobile',
  'A65': 'GetDataGiftPackagesMobile',
  'A66': 'AddVASDataBundlePostPaid',
  'A67': 'AddVASDataBundlePrepaidInit',
  'A68': 'AddVASDataBundlePrepaidConfirm',
  'A69': 'UpdateContact',
  'A70': 'Change-VAS-Password',
  'A71': 'GetBBPackagesV2',
  'A72': 'RegisterForBBFreedom',
  'A73': 'GetServiceDetailRequest',
  'A74': 'GetBBFreedomStatus',
  'A75': 'GetBBPackages',
  'A76': 'GetBBPackageDetails',
  'A77': 'BBPackageChangeRequest',
  'A78': 'GetDashboardVASBundles',
  'A79': 'UpgradeLoyalty',
  'A80': 'VAS Bundle Unsubscription',
  'A81': 'GetDataTransferAmounts',
  'A82': 'ValidateDataTransferSub',
  'A83': 'TransferData',
  'A85': 'ProtocolReport',
  'A86': 'PurchaseAdvancedReportsPrepaidInit',
  'A87': 'PurchaseAdvancedReportsPrepaidConfirm',
  'A88': 'ChangeBBPassword',
  'A89': 'eBillResendRequest',
  'A90': 'BillHistoryRequestV2',
  'A91': 'GetBBPackageComparison',
  'A92': 'ViewUserInfo',
  'A93': 'GetCurrentBBPackage',
  'A94': 'CallForwardingRequest',
  'A95': 'CheckCallForwardingStatus',
  'A96': 'RegisterV2',
  'A97': 'ResendOTPV2',
  'A98': 'eBillCheckUserExist',
  'A99': 'GetCurrentBBPackageV2',
  'A104': 'GetBBPackagesInterim',
  'A105': 'GetPEOPackagesInterim',
  'A106': 'GetVoicePackagesInterim',
  'A107': 'GetFeasibilityCheck',
  'A108': 'ReserveFacility',
  'A109': 'GetCityList',
  'A110': 'UploadMultipartSingle',
  'A111': 'SaveDraft',
  'A112': 'GetDraftDetails',
  'A113': 'CheckExistCustomer',
  'A114': 'GetPaymentLogs',
  'A115': 'UpdatePaymentLogs',
  'A116': 'GetOrderStatus',
  'A117': 'UploadSingle',
  'A118': 'UpdateDraftData',
  'A119': 'GetAvailableProducts',
  'A120': 'GetPurchasedProducts',
  'A121': 'PurchasedProducts',
  'A122': 'ApplicationGenerator',
  'A123': 'ValidateBBPurchaseRequest',
  'A124': 'LogAPIFront',
  'A125': 'GetMovieList',
  'A126': 'GetPackageList',
  'A127': 'CheckOmniTP',
  'A128': 'UpdateISPContact',
  'A129': 'GetPeoTVGOAccessToken',
  'A130': 'CreateServiceRequest',
  'A131': 'CustomerValidation',
  'A132': 'SendOTPRequest',
  'A133': 'VerifyOTPRequest',
  'A134': 'NotificationDetails',
  'A135': 'GetCustConfirmation',
  'A136': 'eBillDownloadRequest',
  'A137': 'EnhancedCurrentDailyUsage',
  'A138': 'EnhancedPreviousDailyUsage',
  'A139': 'PushNotification',
  'A140': 'GetAccessBearerPriceInterim',
  'A141': 'SaveDraftLTE',
  'A142': 'UpdateDraftLTE',
  'A143': 'GetDraftDetailsLTE',
  'A144': 'SaveInvoice',
  'A145': 'UpdateInjvoice',
  'A146': 'GetInvoice',
  'A147': 'BillStatusRequest',
  'A148': 'GetBillCodes',
  'A149': 'BillDownloadRequest',
  'A150': 'NewConSalesLeadCreation',
  'A151': 'SmartBillRegistration',
  'A152': 'GetGoogleAccessToken',
  'A153': 'GoogleRefreshToken',
  'A154': 'AddPopupMessageBanner',
  'A155': '',
  'A156': 'CreateFaultV2'
};

// Get all API numbers and names as array
export const getApiList = () => {
  return Object.entries(apiMapping).map(([number, name]) => ({
    number,
    name
  }));
};
