[SERVICE]
    Flush        1
    Grace        30
    Log_Level    info
    Log_File     C:\Logs\fluent-bit.log
    Parsers_File C:\Program Files\fluent-bit\conf\parsers.conf
    
    # Store logs on disk when backend is down
    storage.path C:\Logs\flb-storage
    storage.sync normal
    storage.checksum off
    storage.backlog.mem_limit 256M

[INPUT]
    Name              tail
    Path              C:\Logs\test.log
    Parser            myslt_csv
    Tag               myslt.logs
    DB                C:\Logs\flb-tail.db
    DB.Sync           normal
    Mem_Buf_Limit     256MB
    storage.type      filesystem
    Read_from_Head    On
    Buffer_Chunk_Size 512k
    Buffer_Max_Size   512k
    Refresh_Interval  1

[FILTER]
    Name          record_modifier
    Match         myslt.logs
    Record        serverIdentifier 192.168.100.114

[OUTPUT]
    Name          http
    Match         myslt.logs
    Host          192.168.100.137
    Port          5001
    URI           /api/logs/ingest/stream
    Header        x-server-id 192.168.100.114
    Format        json
    Compress      gzip
    workers       4
    net.keepalive on
    net.connect_timeout 10s
    net.keepalive_idle_timeout 30s
    storage.total_limit_size 2G
    Retry_Limit   False
